namespace Sunfara.Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; }
public sealed class Channel : Entity { public required string Code { get; set; } public required string Name { get; set; } public string CurrencyCode { get; set; } = "INR"; public string LocaleCode { get; set; } = "en"; }
public sealed class Category : Entity { public required string Name { get; set; } public required string Slug { get; set; } public Guid? ParentId { get; set; } public Category? Parent { get; set; } public List<Category> Children { get; set; } = []; public List<ProductCategory> Products { get; set; } = []; }
public sealed class Vendor : Entity { public required string Name { get; set; } public required string Slug { get; set; } public required string Email { get; set; } public string Status { get; set; } = "pending"; public decimal CommissionRate { get; set; } = 10; public List<Product> Products { get; set; } = []; }
public sealed class Product : Entity { public required string Sku { get; set; } public required string Name { get; set; } public required string Slug { get; set; } public string Type { get; set; } = "simple"; public string? Description { get; set; } public decimal Price { get; set; } public decimal? SpecialPrice { get; set; } public bool IsActive { get; set; } = true; public Guid? ParentId { get; set; } public Product? Parent { get; set; } public List<Product> Variants { get; set; } = []; public Guid? VendorId { get; set; } public Vendor? Vendor { get; set; } public List<ProductCategory> Categories { get; set; } = []; public List<Inventory> Inventories { get; set; } = []; public List<Review> Reviews { get; set; } = []; }
public sealed class ProductCategory { public Guid ProductId { get; set; } public Product Product { get; set; } = null!; public Guid CategoryId { get; set; } public Category Category { get; set; } = null!; }
public sealed class InventorySource : Entity { public required string Code { get; set; } public required string Name { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Inventory : Entity { public Guid ProductId { get; set; } public Product Product { get; set; } = null!; public Guid InventorySourceId { get; set; } public InventorySource InventorySource { get; set; } = null!; public int Quantity { get; set; } public int ReservedQuantity { get; set; } }
public sealed class Customer : Entity { public required string Email { get; set; } public required string FirstName { get; set; } public required string LastName { get; set; } public string? Phone { get; set; } public List<Address> Addresses { get; set; } = []; }
public sealed class Address : Entity { public Guid CustomerId { get; set; } public Customer Customer { get; set; } = null!; public required string AddressLine { get; set; } public required string City { get; set; } public required string State { get; set; } public required string PostalCode { get; set; } public string CountryCode { get; set; } = "IN"; public bool IsDefault { get; set; } }
public sealed class Cart : Entity { public Guid? CustomerId { get; set; } public Customer? Customer { get; set; } public string CurrencyCode { get; set; } = "INR"; public bool IsActive { get; set; } = true; public List<CartItem> Items { get; set; } = []; }
public sealed class CartItem : Entity { public Guid CartId { get; set; } public Cart Cart { get; set; } = null!; public Guid ProductId { get; set; } public Product Product { get; set; } = null!; public int Quantity { get; set; } public decimal UnitPrice { get; set; } }
public sealed class Order : Entity { public required string Number { get; set; } public Guid? CustomerId { get; set; } public Customer? Customer { get; set; } public string Status { get; set; } = "pending"; public string CurrencyCode { get; set; } = "INR"; public decimal Subtotal { get; set; } public decimal Discount { get; set; } public decimal Tax { get; set; } public decimal Shipping { get; set; } public decimal GrandTotal { get; set; } public List<OrderItem> Items { get; set; } = []; }
public sealed class OrderItem : Entity { public Guid OrderId { get; set; } public Order Order { get; set; } = null!; public Guid ProductId { get; set; } public required string Sku { get; set; } public required string Name { get; set; } public int Quantity { get; set; } public decimal UnitPrice { get; set; } public Guid? VendorId { get; set; } }
public sealed class Review : Entity { public Guid ProductId { get; set; } public Product Product { get; set; } = null!; public Guid? CustomerId { get; set; } public int Rating { get; set; } public required string Title { get; set; } public required string Comment { get; set; } public string Status { get; set; } = "pending"; }
public sealed class Coupon : Entity { public required string Code { get; set; } public string Type { get; set; } = "fixed"; public decimal Value { get; set; } public decimal? MinimumOrder { get; set; } public DateTime? StartsAt { get; set; } public DateTime? EndsAt { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Commission : Entity { public Guid OrderItemId { get; set; } public Guid VendorId { get; set; } public decimal GrossAmount { get; set; } public decimal Rate { get; set; } public decimal CommissionAmount { get; set; } public decimal VendorAmount { get; set; } public string Status { get; set; } = "pending"; }
